CREATE TABLE FABRICANTE
(
    ID   BIGSERIAL    NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_FABRICANTE PRIMARY KEY (ID)
);

CREATE TABLE PRODUTO_TIPO
(
    ID BIGSERIAL      NOT NULL,
    TIPO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_PRODUTO_TIPO PRIMARY KEY (ID)
);

CREATE TABLE PRODUTO
(
    ID              BIGSERIAL     NOT NULL,
    NOME            VARCHAR(100)  NOT NULL,
    PRECO_UNITARIO  NUMERIC(10,2) NOT NULL,
    ID_TIPO_PRODUTO BIGINT        NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_TIPO_PRODUTO) REFERENCES PRODUTO_TIPO (ID)
);


CREATE TABLE PRODUTO_DETALHE
(
    ID             BIGSERIAL     NOT NULL,
    ID_PRODUTO     BIGINT        NOT NULL,
    DESCRICAO      VARCHAR(100)  NOT NULL,
    CODIGO_BARRA   VARCHAR(100)  NOT NULL,
    QUANTIDADE      BIGINT       NOT NULL,
    ID_FABRICANTE   BIGINT       NOT NULL,
    CONSTRAINT PK_PRODUTO_DETALHE PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUTO_DETALHE FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID),
    CONSTRAINT FK_PRODUTO_DETALHE_FABRICANTE FOREIGN KEY (ID_FABRICANTE) REFERENCES FABRICANTE (ID)
);

CREATE TABLE USUARIO
(
    ID       BIGSERIAL    NOT NULL,
    NOME     VARCHAR(100) NOT NULL,
    EMAIL    VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20)  NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
    CONSTRAINT USUARIO_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE PAGAMENTO
(
    ID                BIGSERIAL             NOT NULL,
    FORMA             VARCHAR(100)          NOT NULL,
    PARCELAS          VARCHAR(100)          NOT NULL,
    VALOR_TOTAL       NUMERIC(10,2)         NOT NULL,
    VALOR_PARCELA     NUMERIC(10,2)         NOT NULL,
    CONSTRAINT PK_PAGAMENTO PRIMARY KEY (ID)
);

CREATE TABLE ENTREGA
(
    ID   BIGSERIAL    NOT NULL,
    MODO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_ENTREGA PRIMARY KEY (ID)
);

CREATE TABLE PEDIDO
(
    ID           BIGSERIAL   NOT NULL,
    ID_USUARIO   BIGINT      NOT NULL,
    ID_PAGAMENTO BIGINT      NOT NULL,
    ID_ENTREGA   BIGINT      NOT NULL,
    STATUS       VARCHAR(11) NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID),
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID),
    CONSTRAINT FK_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES PAGAMENTO (ID),
    CONSTRAINT FK_ENTREGA FOREIGN KEY (ID_ENTREGA) REFERENCES ENTREGA (ID)
);

CREATE TABLE PEDIDO_PRODUTO
(
    ID         BIGSERIAL NOT NULL,
    ID_PEDIDO  BIGINT    NOT NULL,
    ID_PRODUTO BIGINT    NOT NULL,
    UNIDADES   BIGINT    NOT NULL,
    CONSTRAINT PK_PEDIDO_PRODUTO PRIMARY KEY (ID),
    CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID),
    CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
);